---
name: "Audit"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * 1"
jobs:
  Audit:
    runs-on: "ubuntu-24.04"
    env:
      SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}"
    steps:
    - uses: "actions/setup-go@v5"
      with:
        go-version: "1.24.0"
    - uses: "actions/checkout@v4"
    - run: |
        sudo apt-get update
        sudo apt-get install -y cargo curl
        curl -LO https://downloads.snyk.io/cli/stable/snyk-linux
        sudo cp snyk-linux /bin/snyk
        sudo chmod a+x /bin/snyk
        make -j 4 go
        mage audit
