---
name: "Lint"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
jobs:
  Lint:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: "1.24.0"
    - uses: "actions/checkout@v4"
    - run: |
        sudo apt-get update
        sudo apt-get install -y cargo
        make -j 4
        mage lint
